// Code generated by RandomTsGen

const solveMathProblem = (problem: string): number => {
  const parts = problem.split(" ");
  const operator = parts[1];
  const numbers = parts.slice(2).map((n) => parseInt(n, 10));

  switch (operator) {
    case "+":
      return numbers.reduce((acc, n) => acc + n);
    case "-":
      return numbers[0] - numbers[1];
    case "*":
      return numbers.reduce((acc, n) => acc * n);
    case "/":
      return numbers[0] / numbers[1];
    default:
      throw new Error(`Unsupported operator ${operator}`);
  }
};
